name: Build project

on:
  push:
    branches:
      - 'release/itch'

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
#          - targetPlatform: StandaloneOSX # Build a macOS standalone (Intel 64-bit).
#            channel: mac
#          - StandaloneWindows # Build a Windows standalone.
#            channel: win
#          - targetPlatform: StandaloneWindows64 # Build a Windows 64-bit standalone.
#            channel: win
#          - StandaloneLinux64 # Build a Linux 64-bit standalone.
#            channel: linux
#          - iOS # Build an iOS player.
#          - Android # Build an Android .apk standalone app.
#            channel: android
           - targetPlatform: WebGL # WebGL.
             channel: html5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - name: Compute VERSION via git-describe
        shell: bash
        run: |
          git fetch --tags
          latest=$(git describe --tags --match "v[0-9]*" --abbrev=0)
          commits=$(git rev-list "${latest}"..HEAD --count)
          base=${latest#v}
          if [ "$commits" -gt 0 ]; then
            version="$base.$commits"
          else
            version="$base"
          fi
          echo "VERSION=$version" >> $GITHUB_ENV
      - uses: yeslayla/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.channel }}
          ITCH_GAME: solarpunk-jam
          ITCH_USER: PatrickMoffett
          PACKAGE: build/${{ matrix.targetPlatform }}
          VERSION: ${{ env.VERSION }}